ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= IEP-008: Ldap on Kubernetes

:toc:

.Metadata
[cols="2"]
|===
| IEP
| 8

| Title
| Ldap on Kubernetes

| Author
| link:https://github.com/olblak[Olblak]

| Status
| :speech_balloon: In-process

| Type
| Architecture

| Created
| 2018-01-31
|===



== Abstract

As part of the migration to Azure, the Ldap server must be moved.
We can take this opportunity to containerize this service and move it on a container orchestrator like the kubernetes cluster.
This new architecture change must be done carefully as this is a stateful application with a database that can be corrupted or lead to data loss.

== Specification

This IEP document is about running ldap on Kubernetes on Azure.
Currently the ldap server is running on a bare metal machine and is configured by puppet.
The objective here, is to dockerize this application in order to run it on a kubernetes cluster.

As a stateful application, we must take into consideration following aspect when deploying the ldap server in production.

=== Access
Ldap must be accessible from inside and outside the kubernetes cluster.
In order to reach ldap from the wild, we need a fixed public IP and only allow connection from whitelisted IP.
This can be easily done with the kubernetes resource 'service'.

[cols="1a,2a", options="header"]
.Access
|===
|Inside
|Outside
|
* https://accounts.jenkins.io/[Accountapp]
|
* https://repo.jenkins-ci.org/webapp/#/home[Artifactory]
* https://ci.jenkins.io[ci.jenkins.io]
* https://wiki.jenkins.io/[Confluence]
* https://issues.jenkins-ci.org[Jira]
* puppet master
* spambot
* trusted.ci
|===


=== Backup/Restore
The procedure to backup/restore the database should be easy, two scripts are provided by the same docker image that run ldap. +
Backups must be stored on an Azure File Storage in order to simplify their access from various location. +
A backup name must respect this date format 'YYYYmmddHHMM'

Backups and restore operation should be done in following situations:

[cols="1a,2a", options="header"]
.Backup/Restore
|===
|Backup
|Restore
| * On daily basis
* When the application is stopping
* On demand
| * On demand
|===

=== Certificate
Certificate are loaded at service boot and any certificate change means a service restart.
This can be improved as soon as the container use dynamic configuration.

=== Data
The ldap database must be store on a stable storage that can be easily mounted/unmounted.
Currently there are no perfect solutions as each solution has advantages and disadvanteges.

==== Dedicated Azure Disk storage
ReadWriteOnce
[cols="1a,2a", options="header"]
.Dedicated Azure Disk Storage
|===
|+
|-
|
* Persistent Data across kubernetes clusters as we only have one container running at the time.
* We only have to restore a backup once.
|
* Complexify cluster upgrade, https://github.com/jenkins-infra/iep/tree/master/iep-007[iep-007],
traffic will be redirected to the new server once the old is delete.
* It means downtime when we upgrade the container as we must delete the old container before starting the new one.
|===

==== Dynamic Azure Disk Storage
ReadWriteOnce

[cols="1a,2a", options="header"]
.Dynamic Azure Disk Storage
|===
|+
|-
|
* Persistent data associated to a cluster lifecycle
* Simplify cluster migration, new cluster can be started even if the old cluster is still running
|
* We must restore a backup on each new kubernetes cluster deployment
* While migrating the cluster, we must be sure to put the old cluster in read only mode.
|
|===

==== Azure File storage
ReadWriteMany +
Unfortunately OpenLdap doesn't run well on CIFS partition, so this solution doesn't work at the moment.

==== Conclusion
It seems safer as a first iteration to use a dedicated azure disk storage even if it complexify cluster upgrade.

== Motivation
The motivation here is to benefit from both Kubernetes and Azure services advantages. +
link:https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/[What is Kubernetes?]

== Rationale
== Costs
In addition of the Kubernetes cluster that we are already paying for, we'll need following services

* Public IP
* LoadBalancer
* Azure file storage account for backup
* Disk Storage account for Data

== Reference implementation
* https://github.com/jenkins-infra/ldap[Docker Container]
* https://github.com/jenkins-infra/jenkins-infra/pull/943[Jenkins-infra PR#943]
