ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= IEP-010: Update Center on Azure

:toc:

.Metadata
[cols="2"]
|===
| IEP
| X

| Title
| Update Center on Azure

| Author
| link:https://github.com/olblak[Olivier Vernin]

| Status
| :speech_balloon: In-process

| Type
| [Architecture]

| Created
| 2018-06-01
|===

== Abstract
The link:https://updates.jenkins.io[update center] is a web service that provides information to jenkins instances in order for them to know if core/plugins need to be updated and where to find appropriated updates.
This service is systematically queried by each jenkins instances. It's currently running on the AWS account and need to be migrated to Azure.
This service is a key element of the way we distribute jenkins packages.

== Specification
=== Current State
Currently the service is running on an EC2 instance and it's composed of the following elements:

* An apache webserver that listen on two endpoints.
** link:http://updates.jenkins-ci.org[updates.jenkins-ci.org]
** link:http://updates.jenkins.io[updates.jenkins.io]
* A data directory populated by a shell script ``link:https://github.com/jenkins-infra/update-center2/blob/master/site/generate.sh[generate.sh]`` which is run every 15 minutes from trusted.ci. This script uploads datas via rsync on a linux a machine.

Although the current architecture is quiete stable, there are still places for improvements.

. This web service only contains static files and it would more reliable to just store them on an Azure blob storage.
. We don't need a dedicated machine for this service and so we can move this service on the k8s cluster.

=== URL
By default we use Letsencrypt certificates but its root CA was introduced in java 8u101 which means that we still need another endpoint with a certificate supported by older java versions.
This is why we still need two different endpoint.

* updates.jenkins.io with Letsencrypt
* updates.jenkins-ci.org for old java version

=== Data
Data are generated by a job on trusted.ci.
So if we decide to use an Azure blob storage to store data then we have to update the link:https://github.com/jenkins-infra/update-center2/blob/master/site/generate.sh[script] to use link:https://github.com/Azure/blobxfer[blobxfer] instead of rsync

=== WebServer
This service can easily be dockerized and deployed on the kubernetes cluster. It would be easier to keep using an apache webserver as link:https://github.com/jenkins-infra/update-center2/blob/master/site/generate.sh[generate.sh] generate htaccess files.

== Motivation
Motivations is to increase reliability, availability and scalability of the service.

== Rationale 

WIP...

== Costs
Storage usage and network bandwith will affect the cost.
It's mainly the network bandwith which is affected by 'update-center.json' file size.

== Reference implementation
This design follow the same idea than link:https://github.com/jenkins-infra/iep/tree/master/iep-006[jenkins.io], data on a blob storage and a proxy container on kubernetes.
The only difference here would be the usage of an apache proxy instead of nginx.

